#ifndef BITMAPS_H
#define BITMAPS_H

#include "types.h"

extern const UINT32 cowboy_bitmap[][];
extern const UINT32 cowgirl_bitmap[][];
extern const UINT32 snake_bitmap[][];
extern const UINT32 cactus_bitmap[];
extern const UINT16 cowboy_lives[];
extern const UINT16 cowgirl_lives[];
extern const UINT8 bullet_bitmap[];
extern const UINT8 blank_8[];
extern const UINT32 blank[];
extern const UINT32 cursor[];
extern const UINT16 mouse_cursor[];
extern const UINT16 mouse_cursor2[];
extern const UINT8 arrow1_cursor[];
extern const UINT8 arrow2_cursor[];

#endif
