all: tst_rast tst_mo tst_ren tst_snd showdown 

tst_rast: tst_rast.o raster.o font.o video.o splash.o bitmaps.o
	cc68x -g tst_rast.o raster.o font.o video.o splash.o bitmaps.o -o tst_rast

tst_rast.o: tst_rast.c raster.h types.h video.h splash.h bitmaps.h
	cc68x -g -c tst_rast.c

font.o: font.c font.h types.h
	cc68x -g -c font.c

bitmaps.o: bitmaps.c bitmaps.h types.h
	cc68x -g -c bitmaps.c

raster.o: raster.c raster.h types.h font.h
	cc68x -g -c raster.c

tst_mo: tst_mo.o model.o raster.o font.o events.o video.o random.o
	cc68x -g tst_mo.o model.o raster.o font.o events.o video.o random.o -o tst_mo

tst_mo.o: tst_mo.c model.h events.h random.h
	cc68x -g -c tst_mo.c

model.o: model.c model.h 
	cc68x -g -c model.c

random.o: random.c random.h
	cc68x -g -c random.c

events.o: events.c events.h random.h
	cc68x -g -c events.c

splash.o: splash.c splash.h
	cc68x -g -c splash.c
	
video.o: video.s video.h
	gen -L2 video.s

music.o: music.c music.h types.h
	cc68x -g -c music.c

effects.o: effects.c effects.h types.h psg.h
	cc68x -g -c effects.c

psg.o: psg.c psg.h types.h
	cc68x -g -c PSG.c

input.o: input.c input.h
	cc68x -g -c input.c

tst_snd: tst_snd.o music.o psg.o effects.o
	cc68x -g tst_snd.o music.o psg.o effects.o -o tst_snd

tst_snd.o: tst_snd.c music.h psg.h effects.h
	cc68x -g -c tst_snd.c

tst_ren: tst_ren.o renderer.o font.o model.o events.o bitmaps.o splash.o video.o random.o
	cc68x -g tst_ren.o renderer.o raster.o font.o model.o events.o bitmaps.o splash.o video.o random.o -o tst_ren

renderer.o: renderer.c renderer.h raster.h types.h model.h bitmaps.h events.h splash.h video.h random.h
	cc68x -g -c renderer.c

tst_ren.o: tst_ren.c renderer.h raster.h types.h model.h bitmaps.h events.h splash.h video.h random.h
	cc68x -g -c tst_ren.c

showdown: showdown.o renderer.o font.o model.o events.o bitmaps.o splash.o video.o input.o random.o
	cc68x -g showdown.o renderer.o raster.o font.o model.o events.o bitmaps.o splash.o video.o input.o random.o -o showdown

showdown.o: showdown.c renderer.h raster.h types.h model.h bitmaps.h events.h splash.h video.h input.h random.h
	cc68x -g -c showdown.c
