tst_curr: tst_rast.o raster.o
	cc68x -g tst_curr.o raster.o bitmaps.o model.o events.o renderer.o -o tst_curr

tst_curr.o: tst_curr.c raster.h
	cc68x -g -c tst_curr.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c bitmaps.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

renderer.o: renderer.c renderer.h
	cc68x -g -c renderer.c
